name: Common Steps

description: Common steps for KMP Template workflows

inputs:
  bot-token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    -   name: 🔍 BOT_TOKEN
        if: env.BOT_TOKEN == ''
        env:
            GITHUB_TOKEN: ${{ inputs.bot-token }}
        shell: bash
        run: echo "BOT_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
    -   name: 🔄 Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            token: ${{ env.BOT_TOKEN }}
    - name: ⚙️ Setup Java ☕
      uses: actions/setup-java@v3.13.0
      with:
        distribution: temurin
        java-version: 17
    - name: ⚙️ Setup Gradle 🐘
      uses: gradle/gradle-build-action@v2.9.0
      with:
        dependency-graph: generate-and-submit
