name: Common Steps

description: Common steps for KMP Template workflows

runs:
  using: composite
  steps:
    - name: ⚙️ Setup Java ☕
      uses: actions/setup-java@v4.4.0
      with:
        distribution: temurin
        java-version: 17
    - name: ⚙️ Setup Gradle 🐘
      uses: gradle/gradle-build-action@v3.5.0
      with:
        dependency-graph: generate-and-submit
